### ISSUE TITLE
Documents in synced folders unable to be opened.

### ISSUE THREAD

**Issue by joshcangit** [ONLYOFFICE/snap-desktopeditors#10]
@joshcangit Hi, could you describe your issue with google drive in more details (how do you sync file, via official client or somehow else, your OS and other details) and create separate issue

_Originally posted by @ShockwaveNN in https://github.com/ONLYOFFICE/DesktopEditors/issues/145#issuecomment-449566030_

**Comment by Rita-Bubnova** [comment]
Hi, we were able to reproduce your issue and can confirm it's some kind of bug.

**Comment by XDmitryK** [comment]
This is an unofficial ODrive package and we do not guarantee it will work. Currently Ubuntu uses Nautilus by default to work with files on an online account.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
