### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Gesmir** [ONLYOFFICE/snap-desktopeditors#12]
Hello, when trying to open onlyoffice-desktopeditors 5.2.8 I get the message "Segmentation fault (core dumped)". I'm on Arch Linux with the 4.19.28-1 Kernel.

I also tried it on a fresh fedora (29) installation and got the same error message.

**Comment by sstevan** [comment]
Hey!

I can confirm this issue on Ubuntu 18.04 as well.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
Kernel:  4.15.0-46-generic
```

**Comment by asrosenberg** [comment]
I can confirm as well on Ubuntu 18.04.2 LTS

**Comment by sstevan** [comment]
Hey @XDmitryK,

After removing the `snap` installation I have installed the `.deb` version and it works fine. However, the `snap` version was not working even after reinstalling.

**Comment by ShockwaveNN** [comment]
Can confirm this issue on Ubuntu 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
Kernel:  4.15.0-46-generic
```

**Comment by ShockwaveNN** [comment]
Also can confirm this issue on Fedora 29-1.2 (fresh installed from current latest image)

**Comment by XDmitryK** [comment]
@sstevan @asrosenberg 
We release hotfix for this issue on ubuntu 18.04.2. Please reinstall desktopeditors 
@Gesmir Also on fedora 29 desktopeditors now work fine.
Thanks for your feedback's

**Comment by ShockwaveNN** [comment]
Can confirm that current stable 5.2.8 rev 31 working on Ubuntu 18.04 and Fedora 29-1.2

**Comment by ShockwaveNN** [comment]
Also checked on latest ArchLinux and everythings seems fine too, so I think this issue can be closed. Feel free to reopen it (or create separate issue) if similar problem appear

**Comment by svenv** [comment]
I can confirm this issue on Ubuntu 18.04, using snap to install.
