### ISSUE TITLE
Messy font scheme in ribbon titles

### ISSUE THREAD

**Issue by matveevms** [ONLYOFFICE/snap-desktopeditors#17]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
In the snap version on OS Centos fonts "Helvetica Neue",Helvetica,Arial,sans-serif not load in the top menu and are missing in the font selection menu.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Run snap version of DesktopEditors on OS Centos.
2. Сreate a document.

**What is the expected behavior?**
One of the fonts must be applied in the top menu: "Helvetica Neue",Helvetica,Arial,sans-serif and must be available for selection
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
OS Centos 7.6
snap onlyoffice desktopeditors 5.3.95.43

**Comment by matveevms** [comment]
The problem is no longer relevant on version 8.1.1.27. The default font is Arial. All other specified fonts are missing from the package, as well as on other systems and versions.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
