### ISSUE TITLE
Unable to use input methods

### ISSUE THREAD

**Issue by ericlingit** [ONLYOFFICE/snap-desktopeditors#28]
**Bug report**

**What is the current behavior?**

- Cannot activate input methods like iBus or Fcitx to type Chinese/Japanese/Korean characters.

**Steps to reproduce**

- Install an input method
- Attempt to activate the input method while in OnlyOffice
- Observe that input method doesn't activate

**Expected behavior**
- Input method activates
- Able to input Chinese/Japanese/Korean characters

**Versions**

- OnlyOffice 5.4.1 (snap)
- Ubuntu 19.10 x64

**Did this work in previous versions?**

- No

**Related reports**

- https://github.com/snapcrafters/vscode/issues/28
- https://github.com/snapcrafters/vscode/commit/489d73fb50248cc94a9d39253b38971dff2189c8?diff=unified

**Comment by thanhminhmr** [comment]
Can confirm on KDE Plasma Kubuntu 20.04. This should be a Priority bug, because without input methods, it is impossible to type anything useful with OnlyOffice in language other than English.

**Comment by matveevms** [comment]
Hi, @ericlingit.
I can confirm - this is bug, issue 51953 in our private issue tracker
