### ISSUE TITLE
OnlyOffice doesnt show symbolic links (Folders)

### ISSUE THREAD

**Issue by josefig** [ONLYOFFICE/snap-desktopeditors#29]
Hello,

I'm using Debian 10 and I just installed OnlyOffice using snap. My problem is that it doesn't show the symbolic links I have with a couple of directories since I have different partitions and I created a Documents and Download symbolic links.

I'm not sure if this is related to a permission problem or what could it be?

Thanks!

**Comment by matveevms** [comment]
Hello, @josefig 
I apologize for such a late response, is this problem still relevant now?

**Comment by SirStone** [comment]
It's still relevant for me.

I have this configuration where my Downloads folder is a symlink to /var/tmp. Any document I download can't be open directly from the Download folder, I need to move them in a non-symlinked folder to be able to open the document.

On the other direction, if I want to open a file from the Download folder starting from a running OnlyOffice, clicking on my Download folder doesn't show any file.

This is very annoying

I'm on EndevourOS and using ONLYOFFICE Desktop Editors version 8.0.0.99 (flatpak)

thanks in advance

**Comment by josefig** [comment]
Sorry for the late response, this works perfectly using the deb package, I haven't tested it again with snap.

**Comment by matveevms** [comment]
At this point I have not been able to replicate the problem. Tested on several systems where symbolic links were created. If you have questions about this topic, you can always reopen this issue.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.

**Comment by ken-oyama** [comment]
I still observe this problem today with version 8.2.2 on KDE neon 6.2.
It happens if I install snap using KDE "Discover" package manager.
It doesn't happen if I install .deb downloaded from onlyoffice.com website.
