### ISSUE TITLE
Page setup

### ISSUE THREAD

**Issue by RicardoGausmann** [ONLYOFFICE/snap-desktopeditors#3]
Hello
Congratulations on the beautiful work ONLYOFFICE as SNAP.
I have already installed on my Ubuntu Budgie 17.10 and it is performing very well.
Of course, as the project is new some bugs will be found, so here comes the first one I found. The margins of the odt document are edited 3cm up and left; and 2 cm down and right; originally. However, in the page setup it does not display these values and can not be changed.
The photo below reveals this.
Anything I can do to help you.
Thank you very much for the product !!!

![screen-2018-02-17_02-50-50](https://user-images.githubusercontent.com/34758817/36338162-14592eaa-138f-11e8-895c-c584a199d8ee.jpg)

**Comment by agolybev** [comment]
Hi @RicardoGausmann, thank you for response!
There are paragrapth margins settings in your screenshot. They are 0cm by default.
You can find the page magrins setting in another place:
![desktop](https://user-images.githubusercontent.com/8861642/36377125-efcce6ae-1586-11e8-9f6b-97aaab957473.png)
