### ISSUE TITLE
Cant Ctrl+V images

### ISSUE THREAD

**Issue by sChUhBiDu** [ONLYOFFICE/snap-desktopeditors#32]
**Do you want to request a *feature* or report a *bug*?**
It's a bug.
**What is the current behavior?**
It says "Image is loading" and nothing else happens.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Ctrl+C a picture in google docs, gimp, firefox and when you Ctrl+V in your OnlyOffice Document it doesnt paste the picture.

**What is the expected behavior?**
Pasting a simple image.
**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

**Comment by romandemidov** [comment]
Fixed by https://github.com/ONLYOFFICE/snap-desktopeditors/commit/ccdf4bb164866845148ff4c5d3b2153700bac670
