### ISSUE TITLE
Cannot access files opened from browsers

### ISSUE THREAD

**Issue by jonsnow5** [ONLYOFFICE/snap-desktopeditors#4]
When I click on a file (es. a presentation) on Firefox (but may be another browser) it tells me if I want to open it or save it. If I choose to open it with desktop-editors, it starts but it cannot load the file (it just launch). The issue is that desktopeditors can't read /tmp folder and thus it cannot read those kind of files.
Obvsiously if I save the file to /home partition I can read it.
Probably a solution would be to add content interface and specify /tmp folder.

Anyway thanks for this great software!

**Comment by HellRoad** [comment]
Thanks for your Feedback
Yes lt's a bug, I'll write to the developers

**Comment by Igor-Pigalitsyn** [comment]
Hi @jonsnow5!
Really as you said, the snap package does not have the ability to read files from the temp directory, but you can, save files to `/media` by connecting the interface using the command:
`snap connect onlyoffice-desktopeditors:removable-media`

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
