### ISSUE TITLE
Cannot open email attachements

### ISSUE THREAD

**Issue by KrzysztofW** [ONLYOFFICE/snap-desktopeditors#42]
Hi

This is a serious limitation of the strict confiment of the onlyoffice snap package. In thunderbird when opening an attachment from an email, the attachment file is copied to the /tmp folder which cannot be accessed by onlyoffice because of it's confinement...
Seriously this + opening files from firefox problem makes the snap package of onlyoffice unusable.

Best regards

**Comment by matveevms** [comment]
Hi, @KrzysztofW 
I can confirm - this is bug, issue 49022 in our private issue tracker.

**Comment by romandemidov** [comment]
The normal behavior of snap is to restrict to use the /tmp dir. Snap mounts the local version of /tmp for internal use. 

To avoid the described problem you can set TMP environment variable to user path, e.g. TMP="~/tmp" .

**Comment by KrzysztofW** [comment]
That's not a solution, it's an ugly workaround. /tmp must be accessible by onlyoffice. We can't modify the behavior of all applications to satisfy a restriction in one snap app.

**Comment by matveevms** [comment]
As our staff member already said, we won't be able to fix this as it's technically not possible for a snap package. You can observe similar behavior for other office editors using snap packages. For example, I've checked Libreoffice in snap and I also couldn't open the document from the /tmp folder.
