### ISSUE TITLE
Cannot open files with group permissions

### ISSUE THREAD

**Issue by KrzysztofW** [ONLYOFFICE/snap-desktopeditors#43]
Hi

Onlyoffice installed from a snap package is unable to open files of a different user but with same group.
The file must match the user id, The group permissions are ignored even if the user belogs to the group and the file has read permission for that group.

Regards

**Comment by matveevms** [comment]
Hello, @KrzysztofW 
Would you please attach a video with this problem?

**Comment by KrzysztofW** [comment]
Hi. A video? Why? You can't reproduce it?

**Comment by matveevms** [comment]
Sorry for the delayed response. I can confirm - this is bug, issue 50387 in our private issue tracker

**Comment by matveevms** [comment]
Hello, @KrzysztofW . Received a response from the developers that the access rights for another user are limited by the snap itself, despite the permissions granted. We see the same situation with Snap versions of other text editors. Therefore, this problem cannot be solved from our side.

**Comment by KrzysztofW** [comment]
Hi. Thank you for your reply. OK snaps are a serious limitation. Developers of OnlyOffice and other similar tools should not even bother providing snap packages as they will create a bad user experience.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
