### ISSUE TITLE
Save as or Print dialogs cause desktop-editors to crash

### ISSUE THREAD

**Issue by klebed** [ONLYOFFICE/snap-desktopeditors#55]
Ubuntu 21.04
Snap package onlyoffice-desktopeditors  v6.3.1  rev 81

When trying to open "save as" or "print" dialog, it crashes with error:

(DesktopEditors:18293): Gtk-WARNING **: 18:02:32.886: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unable to load image-loading module: /snap/onlyoffice-desktopeditors/78/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/onlyoffice-desktopeditors/78/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Aborted (core dumped)

**Comment by matveevms** [comment]
Hi, @klebed 
Are you using the default theme in the system or a custom one?
Is the problem repeated on all documents when saving?

**Comment by klebed** [comment]
> Hi, @klebed
> Are you using the default theme in the system or a custom one?
> Is the problem repeated on all documents when saving?

Hi, @matveevms ! 
Default theme.
Any document.

**Comment by matveevms** [comment]
Please provide a screenshot of the "about" window from the settings

**Comment by klebed** [comment]
![image](https://user-images.githubusercontent.com/1313531/131370125-c57e3a3e-918f-4369-9725-4da755b5e48a.png)

**Comment by ShockwaveNN** [comment]
@matveevms Maybe problem in `wayland`? I think we got a lot of problems with wayland setups

**Comment by matveevms** [comment]
I cannot reproduce this problem on my system. Could you record a video of this problem?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
