### ISSUE TITLE
Transparent "Save As" Dialogue

### ISSUE THREAD

**Issue by dimike96** [ONLYOFFICE/snap-desktopeditors#59]
Forgive me if I'm posting this wrong or it's already know, I'm still new to navigating github.

On Ubuntu 20 with desktop editor version 6.2.0.148 I experience a bug when I click "Save As" on a document. The background is transparent and the dialogue is not in a window or anything. This seems to only happen when using a custom theme. The rest of the program behaves fine though, and plenty of others accommodate this without breaking. Hopefully this could be fixed, or someone could provide some info on possible user fixes?
![onlyofficebug](https://user-images.githubusercontent.com/52361278/124522390-183cda80-ddc1-11eb-9b4e-d4af9c6ec494.png)

**Comment by Niwton** [comment]
@matveevms yes, in the screenshot it is using the system window decoration, I would also like to use it, because in KDE Neon the Kwin that is responsible for shadowing the windows cannot draw in OnlyOffice.

**Comment by matveevms** [comment]
@Niwton We do not officially support custom themes. Here I can only suggest the Dark Theme, which we added in previous releases. But if you have examples of office applications that correctly display custom themes and custom visualization, it’s better to create a new issue with a detailed description.

**Comment by romandemidov** [comment]
https://github.com/ONLYOFFICE/snap-desktopeditors/commit/594c34e1ef327de812572c21b857d9e8a9eb4a17
