### ISSUE TITLE
I can not open files directly

### ISSUE THREAD

**Issue by SrStick** [ONLYOFFICE/snap-desktopeditors#6]
When I click on a file it opens on the homepage of onlyoffice, rather than opening the file for editing.

`$ onlyoffice-desktopeditors xxxx.odp 
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.onlyoffice-desktopeditors', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.onlyoffice-desktopeditors', please create it with 0700 permissions.`

from what I could understand, it seems that I have to give some kind of permission to the app, but how do I do it?

**Comment by ShockwaveNN** [comment]
@SrStick seems this warning is unreleated with your problem.
Which OS are you using and can you record a video with your problem?

**Comment by ShockwaveNN** [comment]
This issue is being closed due to no response
