### ISSUE TITLE
Use LZO compression for building the snap

### ISSUE THREAD

**Issue by CompImg** [ONLYOFFICE/snap-desktopeditors#61]
Startup times (first startup after boot) are very long for Onlyoffice on a modern laptop with NVMe SSD.

Canonical has enabled using LZO as a compression format for snaps in order to get better decompression performance for i.e. desktop application snaps. Specifically using LZO compression instead of the default XZ compression will help speedup the time it takes a snap to launch the very first time on a user’s system [1].

I'd kindly ask to enable LZO compression to see if that helps improve startup times. Thanks!

[1] https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714

**Comment by romandemidov** [comment]
https://github.com/ONLYOFFICE/snap-desktopeditors/commit/14d4e69ce47c554f1e1fa8bc3a9dba8ae8f2972c
