### ISSUE TITLE
Cannot access SMB share

### ISSUE THREAD

**Issue by DarkPurpleKnight** [ONLYOFFICE/snap-desktopeditors#68]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

6.4.2.6

### Expected Behavior

FYI, I have installed `onlyoffice-desktopeditors` as a snap package and not as a DEB package. Unfortunately, the snap package is not offered in the **Operating System** drop-down menu.

I wanted to use OnlyOffice to access an SMB share mounted via autofs.

A) In my file manager, the SMB share directory is of course available.
B) In my file manager, I selected OnlyOffice to open a DOCX file that was stored on an SMB share. I expected OnlyOffice to be able to open the DOCX file when OnlyOffice is offered to open the file from the file manager.

### Actual Behavior

A) The directory representing the SMB share does not appear in the OnlyOffice file dialog.
B) OnlyOffice opened, but an empty document appeared, not the contents of the DOCX file.

### Reproduction Steps

1. Install the `[onlyoffice-desktopeditors](https://snapcraft.io/onlyoffice-desktopeditors)` snap package on Linux Mint 20.2
2. Mount an SMB share into the system via autofs.
3. Try to access the SMB share or its contents with OnlyOffice.

### Additional information

I haven't seen a company yet where they don't work with files on SMB shares. I am kind of shocked that OnlyOffice snap package has such problems with this crucial feature.

**Comment by ShockwaveNN** [comment]
Thank you for your report
I can confirm this bug, issue 54557 in our private issue tracker

Seems that problem is actual only for `snap` - for `deb` installation it's working fine

**Comment by DarkPurpleKnight** [comment]
Also the `flatpak` and `AppImage` version of DesktopEditors 6.4.2 can access my SMB share.

**Comment by ShockwaveNN** [comment]
Yeah, that's becasue I've moved this repo to `snap` repo )

**Comment by ShockwaveNN** [comment]
This issue should be fixed, you may need to reinstall package (
```
sudo snap remove onlyoffice-desktopeditors
sudo snap install onlyoffice-desktopeditors
```

And after that SMB shares can be opened correctly

I'm closing this issue but feel free to comment if got any troubles

**Comment by ShockwaveNN** [comment]
Do you reinstalled it? I think reinstallation step is required

And yes, this version from stable is working for me

**Comment by DarkPurpleKnight** [comment]
@ShockwaveNN Yes, I have reinstalled OnlyOffice.

**Comment by ShockwaveNN** [comment]
I'll recheck it on Linux mint, maybe it's OS specific, but i think its more specific to uour system, but to be sure

**Comment by ShockwaveNN** [comment]
I saw a little detail right now

You've said that

> Mount an SMB share into the system via autofs.

But on my system smb is mounted via fstab/cifs

I'm not sure that it's completely different, but I got this entry in my `/etc/fstab` and it's working fine:

```
//192.168.1.1/HomeSamba    /mnt/home-share  cifs   options     0   0
```

I have access to it via `/mnt/home-shape`

Maybe you can try the same?

**Comment by maravento** [comment]
Ubuntu 22.04
Snap: ONLYOFFICE Desktop Editors version 7.0.1.37
Not just SMB. The app also cannot open or save documents from within the app on fstab-mounted partitions. The app can only access /home.

![Captura de pantalla -2022-05-07 18-19-47](https://user-images.githubusercontent.com/14880802/167275060-a87958a6-fa33-4eca-9865-87f732fa17a3.png)

**Comment by ShockwaveNN** [comment]
@maravento Hi, I've just checked mounting my external HDD on Kubuntu 20.04

It's not shown on left panel at all, but if I select it via selecting `/root` partition and entering via `/media` and etc etc - it open file from HDD ok

So I need more details how exactly setup the system so I'll reproduce it

Also please note that like in previous message in this thread - you need to reintstall snap to work properly with mounts

**Comment by Netherquark** [comment]
I have OnlyOffice-Editors from Nobara repos as follows:
`onlyoffice-desktopeditors.x86_64                      7.3.3-50.el7                         @nobara-onlyoffice`

I cannot open files on a local SMB share. I'm using Nobara 37 Gnome, based on Fedora 37 and GNOME 43.2.

**Comment by sliddjur** [comment]
I can open a SMB mounted file if I open it via Nautilus. 
Tested with Ubuntu 23.04 and Gnome. OnlyOffice installed via snap `onlyoffice-desktopeditors  7.4.1`

Steps to reproduce: browse to your smb-share directory. Right click word document or spreadsheet and edit with OnlyOffice. You can now edit and save file.

However, when from OnlyOffice you press open, and the directory-picker will never show any SMB-shares.

**Comment by Netherquark** [comment]
For me it doesnt open either way, through Nautilus or the OO file picker. I'll try running OO in debug mode through the terminal and update the thread.

**Comment by AlexZeitler** [comment]
I'm having the same issue. And if I double click a file from the file share, it gets opened in OO. 

When I'm saving changes in that file, the changes don't get saved without any errors or warnings.

**Comment by celrondraken** [comment]
I mounted the SMB shares in a folder in my filesystem (/home/user/shares) and could click on the directory in onlyoffice using its file browser. 

but then I got "permission denied"

**Comment by XDmitryK** [comment]
I have no problems with SMB on Fedora 39. Changes are saved after editing
![photo_2024-09-04_11-18-56](https://github.com/user-attachments/assets/6345460b-f432-4f0d-baa3-058dc021e318)

**Comment by Rita-Bubnova** [comment]
> I have no problems with SMB on Fedora 39 tested on version snap 8.1.1. Changes are saved after editing

I close this issue. Feel free to comment or reopen it if you got further questions.
