### ISSUE TITLE
Change default folder when saving files

### ISSUE THREAD

**Issue by HellRoad** [ONLYOFFICE/snap-desktopeditors#7]
Currently when saving a file, the root folder where Onlyoffice-Desktopeditors is installed

Files is not saving there, change default folder

Snap revision 25
Ubuntu 18.04

**Comment by XDmitryK** [comment]
This issue no longer occurs
Tested on Fedora 39 snap Onlyoffice Version 8.1.1

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
